version: '3.1'
services:
  # Information needed set up an odoo web
  # application container.
  web-server:
    image: nginx
    container_name: nginx
    depends_on:
      - odoo
    ports:
      # - "8080:80" # Localhost
      - "80:80" # Production
      - 443:443

    # environment:
    #   - NGINX_HOST= localhost # foobar.com
    #   - NGINX_PORT=80
    
    volumes:
      # - ./templates:/etc/nginx/templates # template
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/nginx/ssl # content ./certbot/conf/live/exonus.tech
      - ./certbot/data:/var/www/html
  
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/html --email nathanbangwa@exonus.tech --agree-tos --no-eff-email -d exonus.tech -d www.exonus.tech
    volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/logs:/var/log/letsencrypt
        - ./certbot/data:/var/www/html
    
  odoo:
    image: odoo:15.0
    container_name: odoo
    depends_on:
      - db

    # Port Mapping
    #We need to map the port on the host machine(left side) to the
    #Port inside the container on the right. By default Odoo 
    #Runs on port 8069 and inside the container, it is running on 8069.
    #Locally we are going to access it via localhost:9000

    ports:
      # - "9000:8069"
      # - "80:8069" # without nginx
      - "8069:8069" # with nginx

    restart: always
    
    command: '-u all -d exonus'
    #command: '-u all -d rd-demo'
    #command: '-u all -d bitnami_odoo'

    # Data Volumes
    # --------
    #
    # This defines files that we are sharing from the host machine
    # into the container.
    #
    #Here we are using to map the extra add ons or enterprise addons
    # as well as the configuration file. Also, we need to map the data 
    #directory where Odoo will storesome attachments etc.

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ../community-addons:/mnt/extra-addons
      # - ./addons:/mnt/extra-addons
      # - ./enterprise:/mnt/enterprise

    #Username and password of the Host DB
    # Make sure to give the same credentials
    #inside the postgres service

    environment:
      - HOST=db
      - USER=bn_odoo
      - PASSWORD=bn_odoo
    
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 512M


    # All of the information needed to start up a Postgresql
    # container.
  
  db:
    image: postgres:14
    container_name: postgres_14
    ports:
      - "5432:5432"
    
    restart: always

    #make sure to use the same which were given above.
    environment:
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=bn_odoo
      - POSTGRES_PASSWORD=bn_odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    
    #Add this volume to map the Postgres data. It may be lost
    #if we execute docker-compose down where all the data
    #in the layered file system will be lost
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
      - odoo-db-pgdata:/var/lib/postgresql/data/pgdata
    
    # deployement 
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M

# end services
volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-db-pgdata:
  
