# renew_before_expiry = 30 days
version = 1.22.0
archive_dir = /etc/letsencrypt/archive/exonus.tech
cert = /etc/letsencrypt/live/exonus.tech/cert.pem
privkey = /etc/letsencrypt/live/exonus.tech/privkey.pem
chain = /etc/letsencrypt/live/exonus.tech/chain.pem
fullchain = /etc/letsencrypt/live/exonus.tech/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 2c01e5d83b1839a7f5654ce3146f3b08
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
exonus.tech = /var/www/html
www.exonus.tech = /var/www/html
