# renew_before_expiry = 30 days
version = 1.22.0
archive_dir = /etc/letsencrypt/archive/www.exonus.tech
cert = /etc/letsencrypt/live/www.exonus.tech/cert.pem
privkey = /etc/letsencrypt/live/www.exonus.tech/privkey.pem
chain = /etc/letsencrypt/live/www.exonus.tech/chain.pem
fullchain = /etc/letsencrypt/live/www.exonus.tech/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 5afbcd058320eea4ae33cba2dd0e1332
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
